#!/bin/bash
# Script to test Bug #18 and Bug #19 fixes
# Generated by Claude Code

set -e  # Exit on error

cd /Users/zacharywhitley/git/openabe

echo "=== Testing Bug #18 and Bug #19 Fixes ==="
echo ""
echo "This will:"
echo "1. Clean and rebuild RELIC with BLS12-381 (Bug #19 fix applied automatically)"
echo "2. Rebuild OpenABE source (Bug #18 fix)"
echo "3. Rebuild CLI tools"
echo "4. Run end-to-end CP-ABE test with RELIC + BLS12-381"
echo ""
read -p "Press Enter to continue or Ctrl+C to cancel..."

# Clean and rebuild RELIC
echo ""
echo "=== Step 1: Building RELIC 0.7.0 with BLS12-381 ==="
echo "Cleaning previous build..."
make -C deps/relic clean

echo "Building RELIC (Bug #19 fix will be applied automatically)..."
make -C deps/relic -j8

echo "✅ RELIC built successfully!"

# Rebuild OpenABE source
echo ""
echo "=== Step 2: Building OpenABE Source ==="
make -C src -j8

echo "✅ OpenABE source built successfully!"

# Rebuild CLI
echo ""
echo "=== Step 3: Building CLI Tools ==="
make -C cli -j8

echo "✅ CLI tools built successfully!"

# Run end-to-end test
echo ""
echo "=== Step 4: Running CP-ABE End-to-End Test ==="
cd cli

# Source environment and use RELIC backend
source ../env
unset ZML_LIB

echo "Creating test message..."
echo "Testing RELIC 0.7.0 with BLS12-381 (128-bit security)" > bug18-19-test.txt

echo "Setting up CP-ABE with BLS12-381..."
./oabe_setup -s CP -p bug18-19-test

echo "Generating key for attributes 'one|two'..."
./oabe_keygen -s CP -p bug18-19-test -i 'one|two' -o bug18-19-alice.key

echo "Encrypting with policy '(one and two)'..."
./oabe_enc -s CP -p bug18-19-test -e '(one and two)' -i bug18-19-test.txt -o bug18-19-test.cpabe

echo "Decrypting ciphertext..."
./oabe_dec -s CP -p bug18-19-test -k bug18-19-alice.key -i bug18-19-test.cpabe -o bug18-19-decrypted.txt

echo "Verifying decryption..."
if diff bug18-19-test.txt bug18-19-decrypted.txt > /dev/null 2>&1; then
    echo ""
    echo "✅ ============================================"
    echo "✅  SUCCESS! All tests passed!"
    echo "✅ ============================================"
    echo ""
    echo "Bug #18 (GT API compatibility): FIXED ✅"
    echo "Bug #19 (Sliding window buffer): FIXED ✅"
    echo ""
    echo "OpenABE now supports:"
    echo "  - RELIC 0.7.0 with BLS12-381"
    echo "  - 128-bit security level"
    echo "  - Automated build process"
    echo ""
    echo "Test files created:"
    echo "  - bug18-19-test.txt (original)"
    echo "  - bug18-19-test.cpabe (ciphertext)"
    echo "  - bug18-19-alice.key (user key)"
    echo "  - bug18-19-decrypted.txt (decrypted)"
    echo "  - bug18-19-test.mpk.cpabe (master public key)"
    echo "  - bug18-19-test.msk.cpabe (master secret key)"
    echo ""
else
    echo ""
    echo "❌ FAILED: Decrypted content does not match original!"
    echo ""
    echo "Original:"
    cat bug18-19-test.txt
    echo ""
    echo "Decrypted:"
    cat bug18-19-decrypted.txt
    exit 1
fi
